meta_product_name: "AskAunty"
meta_title: "AskAunty - Just AskAunty!"
meta_description: "Decide what and where to eat when dining in a group"
meta_image: "aunty-square.svg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
